export const FETCH_POKEMONS = 'FETCH_POKEMONS';
export const FETCH_POKEMONS_SUCCESS = 'FETCH_POKEMONS_SUCCESS';
export const FETCH_POKEMONS_FAILURE = 'FETCH_POKEMONS_FAILURE';

export const FILTER_BY_NAME = 'FILTER_BY_NAME';
export const FILTER_BY_TYPE = 'FILTER_BY_TYPE';

export const FETCH_POKEMON_SUCCESS = 'FETCH_POKEMON_SUCCESS';